modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/lumiscosity/no-dialog-warning/issues"
license = "MIT"

[[mods]]
modId = "nodialogwarning"
version = "${version}"
displayName = "No Dialog Warning"
authors = "lumiscosity"
description = '''
Removes the custom dialog warning button
'''
logoFile = "assets/icon.png"

[[dependencies.nodialogwarning]]
modId = "neoforge"
type = "required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nodialogwarning]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "nodialogwarning.mixins.json"
